apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-deploy
  namespace: argocd
spec:
  description: "Project for managing hello-deploy applications"
  sourceRepos:
    - https://github.com/cqqc/test-argocd-helm
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'