apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-deploy
  namespace: argocd
spec:
  project: hello-deploy
  source:
    repoURL: https://github.com/cqqc/test-argocd-helm
    targetRevision: main
    path: charts/hello-deploy
    helm:
      valueFiles:
        - ../../apps/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true