apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: JAVA_OPTS
              value: "-Dspring.config.location=file:/config/application.yaml"
          command: [ "sh", "-c", "java $JAVA_OPTS -jar /home/gradle/hello-deploy-jar-0.0.1-SNAPSHOT.jar" ]
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config